[platformio]
src_dir = Firmware/Hackman3D_Orbit_Controller

[env:sparkfun_promicro16]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
lib_deps=
  https://github.com/NavCoree/3D-controller-Board-package/raw/refs/heads/main/3D_Controller_Board_Package_by_NavCore_v4.zip
  